feat: add migration ci test

diff --git a/.github/workflows/migrate.yml b/.github/workflows/migrate.yml
--- a/.github/workflows/migrate.yml
+++ b/.github/workflows/migrate.yml
@@ -10,8 +10,8 @@ on:
 
 jobs:
 
-  migration-test:
-    name: Migration-Test
+  db-migrator-test:
+    name: db-migrator-test
     runs-on: ubuntu-latest
     services:
       mysql:
@@ -56,6 +56,6 @@ jobs:
         working-directory: ./
       - name: test port-8000
         run: |
-          if [[ `sudo netstat -anltp | grep 8000 | awk '{print $7}'` == "" ]];then echo 'migration-test fail' && exit 1;fi;
-          echo 'migration-test pass'
+          if [[ `sudo netstat -anltp | grep 8000 | awk '{print $7}'` == "" ]];then echo 'db-migrator-test fail' && exit 1;fi;
+          echo 'db-migrator-test pass'
         working-directory: ./
